name: Hello World Workflow

on: 
  push:
    branches:
      - main 
  workflow_dispatch:  

jobs:
  hello_world_1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World 1
        run: echo "Hello World 1"

  hello_world_2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World 2
        run: echo "Hello World 2"
